const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=async(path,opts={})=>{const r=await fetch('/api/'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d};
const money=n=>`$${Number(n||0).toFixed(2)}`;let state={user:null,balance:'0.00',marketItems:[],cart:JSON.parse(localStorage.getItem('mopapay_cart')||'[]'),marketCategory:''};
function toast(m){const t=$('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}}
function openModal(id){const m=$(`#${id}Modal`);if(m)m.setAttribute('aria-hidden','false')}function closeModal(id){const m=$(`#${id}Modal`);if(m)m.setAttribute('aria-hidden','true')}
function route(name){$$('.page').forEach(x=>x.classList.remove('active'));const p=$(`#${name}`);if(p)p.classList.add('active');location.hash=name;loadRoute(name)}
async function saveCart(){localStorage.setItem('mopapay_cart',JSON.stringify(state.cart));updateCartCount()}
function updateCartCount(){const n=state.cart.reduce((a,x)=>a+x.qty,0);const el=$('#cartCount');if(el)el.textContent=n}
function productEmoji(c){return ({Electronics:'📱',Fashion:'👕',Home:'🏠',Beauty:'✨',Services:'🛠️',Digital:'💻',Data:'📶',Other:'🛍️'}[c]||'🛍️')}
function renderTx(items){$('#txTable').innerHTML=items.length?`<div class="table"><div class="tr head"><span>Type</span><span>Amount</span><span>Status</span><span>Date</span></div>${items.map(x=>`<div class="tr"><span>${esc(x.type)}</span><span>${money(x.amount)}</span><span>${esc(x.status)}</span><span>${new Date(x.created_at).toLocaleString()}</span></div>`).join('')}</div>`:'<div class="empty">No transactions yet.</div>'}
function renderAdmin(d){$('#adminUsers').innerHTML=(d.users||[]).map(x=>`<div class="list-row"><b>${esc(x.name)}</b><small>${esc(x.email)} · ${x.role}</small></div>`).join('')||'None';$('#adminWallets').innerHTML=(d.wallets||[]).map(x=>`<div class="list-row"><b>${esc(x.email)} — ${money(x.amount)}</b><small>${x.type} · ${x.reference}</small><button class="btn small" onclick="approve('${x.reference}')">Approve</button></div>`).join('')||'No pending requests';$('#adminAudit').innerHTML=(d.logs||[]).map(x=>`<div class="list-row"><b>${esc(x.action)}</b><small>${esc(x.details||'')}</small></div>`).join('')||'No logs';}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.buy=async id=>{try{await api('marketplace/buy',{method:'POST',body:JSON.stringify({listing_id:id})});toast('Purchase completed');await refreshMe()}catch(e){toast(e.message)}};
window.approve=async ref=>{try{await api('admin/action',{method:'POST',body:JSON.stringify({action:'approve_wallet',reference:ref})});toast('Request approved');renderAdmin(await api('admin'))}catch(e){toast(e.message)}};
async function startDeposit(){const amount=prompt('Enter deposit amount in USD');if(!amount)return;try{const d=await api('payments/start',{method:'POST',body:JSON.stringify({amount})});location.href=d.checkout_url}catch(e){toast(e.message)}}
document.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(o)openModal(o.dataset.open);const c=e.target.closest('[data-close]');if(c)closeModal(c.dataset.close);const r=e.target.closest('[data-route]');if(r)route(r.dataset.route);if(e.target.id==='navLogout')api('auth/logout',{method:'POST'}).then(()=>{state.user=null;updateNav();route('home');toast('Logged out')});if(e.target.id==='depositBtn')startDeposit();if(e.target.id==='cartBtn')route('cart');if(e.target.id==='checkoutBtn'){if(!state.cart.length){toast('Your cart is empty');return}if(!state.user){openModal('login');toast('Please sign in before checkout');return}toast('Checkout is ready. Payment integration can be connected when the provider is active.')}const pill=e.target.closest('.category-pill');if(pill){$$('.category-pill').forEach(x=>x.classList.remove('active'));pill.classList.add('active');state.marketCategory=pill.dataset.cat||'';renderMarket(state.marketItems)}});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target);await api('auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});closeModal('login');await refreshMe();route('dashboard');toast('Welcome back')}catch(x){toast(x.message)}});
$('#registerForm').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target);await api('auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});closeModal('register');await refreshMe();route('dashboard');toast('Account created')}catch(x){toast(x.message)}});
$('#profileForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('profile',{method:'POST',body:JSON.stringify({name:$('#profileName').value})});await refreshMe();toast('Profile saved')}catch(x){toast(x.message)}});
$('#walletRequestForm').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target);const d=Object.fromEntries(f);await api('wallet/request',{method:'POST',body:JSON.stringify(d)});e.target.reset();toast('Request submitted for admin review')}catch(x){toast(x.message)}});
$('#listingForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));d.action='create_listing';await api('admin/action',{method:'POST',body:JSON.stringify(d)});e.target.reset();toast('Listing published')}catch(x){toast(x.message)}});
$('#marketSearch').addEventListener('input',()=>renderMarket(state.marketItems));$('#marketSort').addEventListener('change',()=>renderMarket(state.marketItems));$('#year').textContent=new Date().getFullYear();updateCartCount();
$('#contactForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('contact',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();toast('Message sent')}catch(x){toast(x.message)}});
(async()=>{const p=new URLSearchParams(location.search);if(p.get('payment')==='success')toast('Payment received. Your wallet will update after server verification.');try{await refreshMe()}catch{}route(location.hash.slice(1)||'home')})();
